#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Inside pre-push"

#!/bin/sh
branch="$(git rev-parse --abbrev-ref HEAD)"
regex = "^(CR-[0-9]+_)([a-zA-Z0-9_-]+\.?)+$|^hotfix-(CR-[0-9]+_)([a-zA-Z0-9_-]+\.?)+$"

if ! [[ $branch =~ $regex ]]; then
  echo "Incorrect Branch Name"
  exit 1
fi

if [[ "$branch" == "main" ]]; then
  echo "Pushing to the 'main' branch is not allowed."
  exit 1
fi

# If both conditions are met, allow pushing:
echo "Pushing to branch '$branch'..."
