#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#!/bin/sh
branch="$(git rev-parse --abbrev-ref HEAD)"
regex = "^(main|develop|[A-Z]+-\\d+_\\S+)$",

if ! [[ $branch =~ $regex ]]; then
  echo "Incorrect Branch Name"
  exit 1
fi