#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#!/bin/sh
branch="$(git rev-parse --abbrev-ref HEAD)"
regex = "^(CR-[0-9]+_)([a-zA-Z0-9_-]+\.?)+$|^hotfix-(CR-[0-9]+_)([a-zA-Z0-9_-]+\.?)+$"

if ! [[ $branch =~ $regex ]]; then
  echo "Incorrect Branch Name"
  exit 1
fi